# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e2d4b082ade017de864a5fdbd06b021ee9ec5389c55a31a1afdd6a4bdccb06816ae05a10fbc97ef0ec8a4ffca2b8efdf6e34e457f7684137aaf7369df305af5d

test:
  secret_key_base: 5aadabaa370f732bdc2186c9a0636119f47a0da1d56fd56c9692e9811c3d29510865ca125773d8b61aa35a735285ac3c7ce42a3c46865eb5b687e879ea3d861e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
